name: Build LaTeX PDF

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex

      - name: Upload PDF
        uses: actions/upload-artifact@v2
        with:
          name: IG-Thesis-PDF
          path: main.pdf
